### ISSUE TITLE
Add more UI tests

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#1040]
This issue just collects possible test cases for UI tests.

## Test cases

Feel free to just add to this list.

- [ ] Login works: start page, click login button, enter credentials, click login again (or press enter?), make sure user is logged in
- Language
  - [ ] Language menu exists in header, can be used to change the language
  - [ ] Automatic language detection works (no idea how hard this is with UI testing frameworks)
- Video page
  - [ ] Player exists, loads and can be used to play
  - [ ] All metadata (for a specific video) exists on the page
  - [ ] Other videos of that series are shown below and can be clicked.
  - [ ] Share button exists, can be clicked, reveals share menu
- Realm editing
  - [ ] Name can be changed (fixed & derived)
  - [ ] Order of subpages can be changed
  - [ ] Path can be changed (and all links on the page are updated accordingly without reload!)
  - [ ] Page can be deleted
  - [ ] Adding sub-page works
  - Blocks
    - [ ] Text block can be added & edited
    - [ ] Title block can be added & edited
    - [ ] Video block can be added & edited (and layout options work)
    - [ ] Series block can be added & edited (and layout options work)
    - [ ] Block can be removed
  - [ ] All the above things should also be tested for user pages
- [ ] Adding user page works
- Search
  - [ ] Shortcut "s" works
  - [ ] Entering input shows search results

**Comment by owi92** [comment]
I wrote extensive tests for realm editing (including user pages) that would tick all the boxes, but these are still flaky. I tried multiple times to fix this, but couldn't get it working reliably. There appears to be an issue where the api/db access is sometimes too slow, making these fail. And while there are mechanisms in playwright that should in theory help with this, none of them seemed to help. This is really bugging me.
