### ISSUE TITLE
Note taking: DB fields of event, series, ...

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#162]
This issue is basically a notepad for moments where I notice "we need to store this thing in the database". Feel free to edit this top comment to add stuff.

#### Event//video
- [x] Duration in subseconds maybe. We can pass that to the player to be able to show the duration without starting to load the media.
- [x] Aspect ratio: we don't want the layout to jump around, so being able to know the aspect ratio before the player loaded the media is a good idea.
- [x] List of media, each with quality and URL. Should this be normalized as an extra table or just be an array or even JSON column?
- [ ] Poster: image that can be used as background for the player before the media is played. Probably just the thumbnail in large.
- [ ] Language
- [ ] Subject
- [ ] Extended metadata
- [ ] File attachements

#### Series
- ...

**Comment by LukasKalbertodt** [comment]
I don't think this issue serves a purpose anymore.
