### ISSUE TITLE
Tracking issue: Design stuff

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#226]
This is really just a list of design/frontend stuff I still have to do. I don't want to create a new issue for each of these tiny things. I will constantly add new items to this list.

- [x] Adjust logo margins in header. When the screen is small, it should still be able to maintain required margins. But the header should obviously also not overflow. 
- [x] Replace all hardcoded colors with colors from theme
- [x] Footer
- [ ] When there are a lot of realms, in the burger menu, the management links and normal realm links blend together. There should be a gap or sth.
- [ ] Maybe 3 lines for realm names in the navigation are too many. Maybe we should max out at 2. (Tho: 2 is fairly little text content on medium small screens)
- [ ] Design custom radio buttons and check boxes? If we want to color them in our colors, we need to.
- [x] ~~Is the name "accent" a good one for this one color? Maybe "action"? Maybe "contrast"? (Tho: "accent" is fairly general so it's fine I guess)~~ We kept "accent", and there is really no urge to change it
- [ ] Experiment: color management links different than normal navigation links.
