### ISSUE TITLE
Add more metrics

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#562]
#561 added the initial metrics endpoint with a few useful metrics. Here is list of metrics we could still add (if you can edit this comment, feel free to add items to this list).

- [ ] Times required to acquire a connection to the DB (from the DB pool)
- [ ] Number of 5xx replies
- [ ] Number of panics in handlers
- [ ] Number of logged errors (arguably, one should use a proper log aggregator and setup alerts that way. Buuut that's work and if people have already a Prometheus setup, maybe reporting the number of errors as a metric helps?)
- [ ] Number of items indexed for search (tho that is information only the `tobira worker` has)
- [ ] Number of active database connections (though maybe that should be reported by a postgres exporter?)
- [ ] Number of bytes received and sent out?
- [ ] Some tokio metrics (there is an unstable library for that).
- [ ] More memory allocation metrics?
- [ ] Number of active users in the past X hours.
